server:
  port: 8082 # Un puerto diferente al buscador

spring:
  application:
    name: ms-books-payments # Nombre para Eureka
  datasource:
    url: jdbc:h2:mem:paymentsdb # BD Relacional propia
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    enabled: false
    # serviceUrl:
    #   defaultZone: http://localhost:8761/eureka/ # URL de tu servidor Eureka